### ISSUE TITLE
Possibility to reuse official AWX installer ?

### ISSUE THREAD

**Issue by aelbarkani** [geerlingguy/tower-operator#17]
Hi @geerlingguy,

Thank you very much for this work. I have a question regarding the Ansible roles you are using. Did you assess the pros and cons of reusing the official AWX roles in your operator ?
https://github.com/ansible/awx/tree/devel/installer

**Comment by geerlingguy** [comment]
@aelbarkani - Yes, I spent a bit of time churning through all that code (and looking at the Tower installer for OpenShift), and it adds a lot of complexity that this operator _currently_ doesn't want to support.

However, long-term, my idea would be to use a shared role for the Kubernetes deployment of AWX and Tower (and this Tower/AWX Operator) so the installation can be completely standardized.

Unfortunately, it will likely require a bit of complexity beyond what this operator is currently doing, since there are a lot of different security policies the official installer has to account for that I'm conveniently ignoring for more vanilla Kubernetes deployments :)

**Comment by geerlingguy** [comment]
The issue to follow for this, though, is: https://github.com/geerlingguy/tower-operator/issues/11
