### ISSUE TITLE
Can't scale the deployments and statefulset

### ISSUE THREAD

**Issue by eas75034** [geerlingguy/tower-operator#20]
If you scale the deployments, and statefulset higher than 1 replica, they will get automatically scaled back down to 1. Why is this? How can I make it so I can scale higher than one?

**Comment by eas75034** [comment]
It looks like the deployments for the memcached, rabbitmq, tower_task, and tower_web are all owned by the tower resource. This is why my changes at the deployment spec for the replicas was getting automatically revert back to 1. Is there a key/value reference I can use in the tower spec to control the number of replicas for the deployments? Same question regarding the postgres statefulset.

**Comment by geerlingguy** [comment]
Currently, I'm not sure exactly how things will behave if you use more than one instance... some service may work okay, others may not (split-brained and all that—especially Postgres, but maybe also memcached and rabbit since they might need more config to work with more than one running pod).

But it is something that should be configurable, assuming the underlying service can scale beyond one Pod without everything breaking.
