### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by stobias123** [geerlingguy/tower-operator#22]
Operator container shows the below.
```
 File "/usr/local/lib/python3.6/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/opt/ansible/.ansible/tmp): [Errno 13] Permission denied: b'/opt/ansible/.ansible/tmp'
```

**Comment by geerlingguy** [comment]
@stobias123 - Strange; can you provide more details about the cluster environment? E.g. is it OpenShift, local Minikube, or something else?

The local directory should be inside the ansible container, and that seems like it shouldn't even have the possibility of failing since it's not on a shared filesystem or PV or anything like that.

**Comment by stobias123** [comment]
vanilla k8s. running on rancher. 

This was resolved when I  rolled back tower operator image from 0.2.2 to 0.2.1 - haven't tried with more recent images.

**Comment by geerlingguy** [comment]
Interesting, there weren't any substantial changes in the 0.2 release series, except for the actual Tower version being updated (to I think 3.6.1 or 3.6.2?), so maybe it's an upstream issue with that version of Tower / AWX?

**Comment by stobias123** [comment]
Could be. Feel free to close this issue. I don't see it any longer. Maybe
it was some other funky thing I had going on.

**Comment by geerlingguy** [comment]
Sounds good. Please re-open if you find it happening again!
